version: '3.4'

services:
  learning.shop.api:
    image: ${DOCKER_REGISTRY-}learningshopapi
    build:
      context: .
      dockerfile: Learning.Shop.API/Dockerfile
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - esnetwork
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    networks:
      - esnetwork
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
networks:
  esnetwork:
    driver: bridge    